/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DateTime } from "./DateTime";
export type { Game2048 } from "./Game2048";
export type { KaijuGameFactory } from "./KaijuGameFactory";
export type { KaijuGameNFT } from "./KaijuGameNFT";
