service: kaijuWebGame
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  timeout: 60
  region: ${file(./env.yml):${self:provider.stage}.REGION}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: "Allow"
          Action: [ "ses:SendEmail",
                    "ses:SendRawEmail"]
          Resource: "*"
  environment:
    REGION: ${file(./env.yml):${self:provider.stage}.REGION}
    STAGE: ${self:provider.stage}
    AWS_ACCOUNT_ID: ${file(./env.yml):${self:provider.stage}.AWS_ACCOUNT_ID}
    SERVICE: ${self:service}
    MONGODB_URL: ${file(./env.yml):${self:provider.stage}.MONGODB_URL}
    DB_NAME: ${file(./env.yml):${self:provider.stage}.DB_NAME}

functions:
  PaymasterSign:
    handler: functions/paymasterSign/paymasterSign.handler
    events:
      - http:
          path: /paymasterSignjs
          method: post

  gameRewards:
    handler: functions/gameRewards.gameRewards
    environment:
      RPC_URL: ${file(./env.yml):${self:provider.stage}.RPC_URL}
      PRIVATE_KEY: ${file(./env.yml):${self:provider.stage}.PRIVATE_KEY}
      GAME_FACTORY_CONTRACT: ${file(./env.yml):${self:provider.stage}.GAME_FACTORY_CONTRACT}
      KAIJU_TOKEN_CONTRACT: ${file(./env.yml):${self:provider.stage}.KAIJU_TOKEN_CONTRACT}
      USDT_CONTRACT: ${file(./env.yml):${self:provider.stage}.USDT_CONTRACT}
      KARC_REWARD_1: ${file(./env.yml):${self:provider.stage}.KARC_REWARD_1}
      KARC_REWARD_2: ${file(./env.yml):${self:provider.stage}.KARC_REWARD_2}
      KARC_REWARD_3: ${file(./env.yml):${self:provider.stage}.KARC_REWARD_3}
      KARC_REWARD_4: ${file(./env.yml):${self:provider.stage}.KARC_REWARD_4}
      USDT_REWARD_1: ${file(./env.yml):${self:provider.stage}.USDT_REWARD_1}
      USDT_REWARD_2: ${file(./env.yml):${self:provider.stage}.USDT_REWARD_2}
      USDT_REWARD_3: ${file(./env.yml):${self:provider.stage}.USDT_REWARD_3}
      USDT_REWARD_4: ${file(./env.yml):${self:provider.stage}.USDT_REWARD_4}
      KARC_DECIMAL: ${file(./env.yml):${self:provider.stage}.KARC_DECIMAL}
      USDT_DECIMAL: ${file(./env.yml):${self:provider.stage}.USDT_DECIMAL}
  
  paymasterBalanceCheck:
    handler: functions/paymasterBalanceCheck.paymasterBalanceCheck
    environment:
      PAYMASTER_CONTRACT: ${file(./env.yml):${self:provider.stage}.PAYMASTER_CONTRACT}
      PAYMASTER_THRESHOLD_VALUE: ${file(./env.yml):${self:provider.stage}.PAYMASTER_THRESHOLD_VALUE}
      FROM_ADDRESS: ${file(./env.yml):${self:provider.stage}.FROM_ADDRESS}
      TO_ADDRESS: ${file(./env.yml):${self:provider.stage}.TO_ADDRESS}
      RPC_URL: ${file(./env.yml):${self:provider.stage}.RPC_URL}